-- Create the Board table
CREATE TABLE IF NOT EXISTS BOARD_TABLE (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL

);

-- Create the Column table
CREATE TABLE COLUMN_TABLE (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    BOARD_ID INT NOT NULL,
    FOREIGN KEY (BOARD_ID) REFERENCES BOARD_TABLE(ID) ON DELETE CASCADE
);

-- Create the Task table
CREATE TABLE TASK_TABLE (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    COLUMN_ID INT NOT NULL,
    FOREIGN KEY (COLUMN_ID) REFERENCES COLUMN_TABLE(ID) ON DELETE CASCADE
);

-- Create the Subtask table
CREATE TABLE SUBTASK_TABLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    COMPLETED BOOLEAN NOT NULL,
    TASK_ID INT NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES TASK_TABLE(ID) ON DELETE CASCADE
);

